# Generated by Django 5.1.2 on 2024-11-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
