# Generated by Django 5.1.4 on 2024-12-18 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_myuser_is_online_myuser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='users_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
