# Generated by Django 5.1.4 on 2024-12-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0003_alter_myuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='activation_code',
        ),
        migrations.AddField(
            model_name='myuser',
            name='backup_codes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
